spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mail-grub
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=10m

logging:
  level:
    org:
      springframework: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}

com:
  mailgrub:
    firebase:
      web-api-key: ${FIREBASE_WEB_API_KEY}
      credentials: ${FIREBASE_CREDENTIALS}
